version: "3"
services:
  social-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: social-microservice
    restart: unless-stopped
    tty: true
    environment:
        APP_NAME: social-microservice
    ports:
      - 8027:80  # Adjust the port as needed
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Add other volume mappings if necessary
    networks:
      - user-network

  social-database:
    image: mysql:5.7.22
    container_name: social-database
    restart: unless-stopped
    tty: true
    ports:
      - "33080:3306"
    environment:
      MYSQL_DATABASE: social-database
      MYSQL_ROOT_PASSWORD: "password"  # Adjust as needed
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata-social:/var/lib/mysql
    networks:
      - user-network

  social-webserver:
    image: nginx:alpine
    container_name: social-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3083:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - user-network

networks:
  user-network:
    external: true
    driver: bridge

volumes:
  dbdata-social:
    driver: local
