version: "3"
services:
  gateway-microservice:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: digitalocean.com/php
    container_name: gateway-microservice
    restart: unless-stopped
    tty: true
    environment:
        APP_NAME: gateway-microservice
    ports:
      - 8025:80  # Adjust the port as needed
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Add other volume mappings if necessary
    networks:
      - user-network

  gateway-database:
    image: mysql:5.7.22
    container_name: gateway-database
    restart: unless-stopped
    tty: true
    ports:
      - "33078:3306"
    environment:
      MYSQL_DATABASE: gateway-database
      MYSQL_ROOT_PASSWORD: "password"  # Adjust as needed
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata-gateway:/var/lib/mysql
    networks:
      - user-network

  gateway-webserver:
    image: nginx:alpine
    container_name: gateway-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3081:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - user-network

networks:
  user-network:
    external: true
    driver: bridge

volumes:
  dbdata-gateway:
    driver: local
