version: "3"
services:
  book-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: book-microservice
    restart: unless-stopped
    tty: true
    environment:
        APP_NAME: book-microservice
    ports:
      - 8026:80  # Adjust the port as needed
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Add other volume mappings if necessary
    networks:
      - user-network

  book-database:
    image: mysql:5.7.22
    container_name: book-database
    restart: unless-stopped
    tty: true
    ports:
      - "33079:3306"
    environment:
      MYSQL_DATABASE: book-database
      MYSQL_ROOT_PASSWORD: "password"  # Adjust as needed
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata-book:/var/lib/mysql
    networks:
      - user-network

  book-webserver:
    image: nginx:alpine
    container_name: book-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "3082:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - user-network

networks:
  user-network:
    external: true
    driver: bridge

volumes:
  dbdata-book:
    driver: local
