version: "3"
services:
  user-microservice:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: digitalocean.com/php
    container_name: user-microservice
    restart: unless-stopped
    tty: true
    environment:
        APP_NAME: user-microservice
    ports:
      - 8024:80  # Adjust the port as needed
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Add other volume mappings if necessary
    networks:
      - user-network
  user-db:
    image: mysql:5.7.22
    container_name: user-db
    restart: unless-stopped
    tty: true
    ports:
      - "33077:3306"
    environment:
          MYSQL_DATABASE: user-db
          MYSQL_ROOT_PASSWORD: "passwd"
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
    volumes:
      - dbdata-user:/var/www
    networks:
      - user-network
  user-webserver:
    image: nginx:alpine
    container_name: book-webserver-authorization
    restart: unless-stopped
    tty: true
    ports:
      - "3080:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
        - user-network
networks:
  user-network:
    external: true
    driver: bridge

volumes:
  dbdata-user:
    driver: local
